use customer_behaviour;
select * from customer;
# what is the total revenua generated by male vs female customers?
select gender , sum(purchase_amount) as revenue from customer group by gender;
#which customers used a discount  but still  spent more   than avg purchase amount?
select  customer_id,purchase_amount from customer
 where discount_applied ="yes" and  purchase_amount>=(select avg(purchase_amount) from customer);
#select top 5  products with the  highest average review rating ?
select item_purchased ,ROUND(avg(review_rating),2)as "review_rating" from customer 
group by item_purchased 
order by avg(review_rating)desc 
limit 5;
-- COMPARE THE AVERAGE PURCHASE AMOUNTS BETWEEN STANDARD AND EXPRESS  SHIPPING
SELECT AVG(PURCHASE_AMOUNT)AS "PURCHASE AMOUNT",SHIPPING_TYPE  FROM CUSTOMER
 WHERE SHIPPING_TYPE IN ('STANDARD',
 'EXPRESS') GROUP BY SHIPPING_TYPE;
--   DO SUBSCRIBED  CUSTOMERS SPEND MORE ? COMPARE AVERAGE  SPEND AND TOTAL REVENUE BETWEEN  SUBSCRIBERS AND NON SUBSCRIBERS
SELECT SUBSCRIPTION_STATUS,COUNT(CUSTOMER_ID)AS TOTAL_NUMBERS,
AVG(PURCHASE_AMOUNT) AS AVG_SPEND ,
 SUM(PURCHASE_AMOUNT)AS TOTAL_REVENUE 
 FROM CUSTOMER
GROUP BY SUBSCRIPTION_STATUS
ORDER BY TOTAL_REVENUE, AVG_SPEND DESC;
-- WHICH PRODUCT HAVE HIGHEST  PERCENTAGE OF PURCHASES WITH DISCOUNT APPLIED
SELECT  ITEM_PURCHASED,ROUND(100*SUM(CASE WHEN DISCOUNT_APPLIED='YES'THEN 1 ELSE 0 END)/COUNT(*),2)AS DISCOUNT_RATE FROM CUSTOMER
GROUP BY ITEM_PURCHASED
ORDER BY DISCOUNT_RATE DESC
LIMIT 5;
-- segment customers into new ,returning ,and loyal based on  their total number of previous purchases,and show the count of each segment.-- 
with customer_type as(select customer_id,previous_purchases,
case when previous_purchases=1 then 'new'
when previous_purchases between 2 and 10 then 'returning'
else 'loyal' end 
as customer_segment
 from customer)
select customer_segment, count(*)as 'number of customers' from customer_type
group by customer_segment;
-- top 3 products in each category-- 
with item_count as(
select categorypurchase, item_purchased, count(customer_id) as total_orders,
row_number()over(partition by categorypurchase order by count(customer_id) desc) as item_rank 
from customer group by categorypurchase,item_purchased
)
 select item_rank, categorypurchase,item_purchased,total_orders from item_count where  item_rank <=3;
-- are customers who are repeat buyers( more than 5previous purchases)also likely to subscribe?
  select subscription_status,
  count(customer_id)as repeat_buyers 
  from customer where previous_purchases>5
  group by subscription_status;
--   check revenue by age group 
select age_group,sum(purchase_amount)as total_revenue from customer
group by age_group
order by total_revenue desc;